# Data Cleaning

In [1]:
import numpy as np
import pandas as pd

In [2]:
import os
os.getcwd()

'C:\\Users\\hp\\Downloads\\Churn Project\\Churn Project'

In [3]:
os.listdir()

['.ipynb_checkpoints',
 'Churn _Dataset _Cleaning.ipynb',
 'Churn_Analysis.sql',
 'Churn_Clean_Data.csv',
 'Churn_Unclean_Data.xlsx']

In [4]:
%pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
df = pd.read_excel('Churn_Unclean_Data.xlsx')

In [6]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000+A2:A534,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 542 entries, 0 to 541
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            542 non-null    object
 1   Customer_Name          533 non-null    object
 2   Gender                 536 non-null    object
 3   Age                    536 non-null    float64
 4   State                  531 non-null    object
 5   City                   539 non-null    object
 6   Tenure_Months          534 non-null    float64
 7   Subscription_Type      530 non-null    object
 8   Monthly_Charges        529 non-null    float64
 9   Total_Charges          533 non-null    float64
 10  Contract_Type          538 non-null    object
 11  Payment_Method         526 non-null    object
 12  Internet_Service       535 non-null    object
 13  Tech_Support           530 non-null    object
 14  Senior_Citizen         534 non-null    object
 15  Dependents             539 non-null    object
 16  Churn                  538 non-null    object
 17  Last_Interaction_Date  539 non-null    object
dtypes: float64(4), object(14)
memory usage: 76.3+ KB

In [8]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  536.000000     534.000000       529.000000     533.000000
mean    44.399254      36.406367      1335.269206   49745.287336
std     18.556837      20.669599       715.972838   41644.111657
min      3.000000       1.000000     -2454.770000  -99781.820000
25%     30.000000      19.000000       756.570000   18770.290000
50%     44.000000      38.000000      1306.800000   40649.600000
75%     57.000000      54.000000      1900.650000   75647.400000
max    165.000000      72.000000      2492.510000  171429.830000

In [9]:
df.shape

(542, 18)

In [10]:
df.isnull().sum()

Customer_ID               0
Customer_Name             9
Gender                    6
Age                       6
State                    11
City                      3
Tenure_Months             8
Subscription_Type        12
Monthly_Charges          13
Total_Charges             9
Contract_Type             4
Payment_Method           16
Internet_Service          7
Tech_Support             12
Senior_Citizen            8
Dependents                3
Churn                     4
Last_Interaction_Date     3
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(16)

In [12]:
df.drop_duplicates(inplace=True)

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.shape

(526, 18)

In [15]:
df.replace(['N/A', 'NULL', '', ' '],np.nan, inplace=True)

In [16]:
df.isnull().sum()

Customer_ID               0
Customer_Name             7
Gender                    5
Age                       5
State                    10
City                      4
Tenure_Months             7
Subscription_Type        10
Monthly_Charges          11
Total_Charges             7
Contract_Type             3
Payment_Method           14
Internet_Service          6
Tech_Support             11
Senior_Citizen            7
Dependents                2
Churn                     3
Last_Interaction_Date     2
dtype: int64

In [17]:
df=df.apply(lambda x:x.str.strip() if x.dtype=="object" else x)

In [18]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000+A2:A534,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 526 entries, 0 to 532
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            526 non-null    object
 1   Customer_Name          519 non-null    object
 2   Gender                 521 non-null    object
 3   Age                    521 non-null    float64
 4   State                  516 non-null    object
 5   City                   522 non-null    object
 6   Tenure_Months          519 non-null    float64
 7   Subscription_Type      516 non-null    object
 8   Monthly_Charges        515 non-null    float64
 9   Total_Charges          519 non-null    float64
 10  Contract_Type          523 non-null    object
 11  Payment_Method         512 non-null    object
 12  Internet_Service       520 non-null    object
 13  Tech_Support           515 non-null    object
 14  Senior_Citizen         519 non-null    object
 15  Dependents             524 non-null    object
 16  Churn                  523 non-null    object
 17  Last_Interaction_Date  524 non-null    object
dtypes: float64(4), object(14)
memory usage: 78.1+ KB

In [20]:
df["Customer_Name"]=df["Customer_Name"].str.title()
df["State"]=df["State"].str.title()
df["Gender"]=df["Gender"].str.title()
df["City"]=df["City"].str.title()
df["Subscription_Type"]=df["Subscription_Type"].str.title()
df["Contract_Type"]=df["Contract_Type"].str.title()
df["Payment_Method"]=df["Payment_Method"].str.title()
df["Internet_Service"]=df["Internet_Service"].str.title()
df["Tech_Support"]=df["Tech_Support"].str.title()
df["Senior_Citizen"]=df["Senior_Citizen"].str.title()
df["Dependents"]=df["Dependents"].str.title()
df["Churn"]=df["Churn"].str.title()

In [21]:
df['Churn'].value_counts()

Churn
No     397
Yes    126
Name: count, dtype: int64

In [22]:
cols=['Age','Tenure_Months','Monthly_Charges','Total_Charges']
for c in cols:
    df[c]=pd.to_numeric(df[c],errors="coerce")

In [23]:
df=df[(df['Age']>=18)&(df['Age']<=100)]

In [24]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  512.000000     505.000000       502.000000     505.000000
mean    43.455078      36.334653      1332.008108   49895.053109
std     15.469999      20.483367       717.998378   40996.389276
min     18.000000       1.000000     -2454.770000  -99781.820000
25%     30.000000      19.000000       758.627500   19006.700000
50%     43.000000      38.000000      1300.700000   40687.790000
75%     56.250000      54.000000      1879.555000   73102.920000
max     70.000000      72.000000      2492.510000  171429.830000

In [25]:
df=df[(df['Monthly_Charges']>=0)]
df=df[(df['Total_Charges']>=0)]
df=df[(df['Tenure_Months']>=0)]

In [26]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  482.000000     482.000000       482.000000     482.000000
mean    43.307054      36.000000      1361.941846   50097.449959
std     15.446949      20.380681       651.482686   39491.310187
min     18.000000       1.000000       302.540000     354.120000
25%     30.000000      19.000000       763.560000   19047.500000
50%     43.000000      38.000000      1311.000000   40668.695000
75%     56.000000      53.000000      1884.297500   73094.590000
max     70.000000      72.000000      2492.510000  171429.830000

In [27]:
df.shape

(482, 18)

In [28]:
df['Last_Interaction_Date']=pd.to_datetime(df['Last_Interaction_Date'],errors='coerce')

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 482 entries, 0 to 532
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            482 non-null    object
 1   Customer_Name          477 non-null    object
 2   Gender                 478 non-null    object
 3   Age                    482 non-null    float64
 4   State                  475 non-null    object
 5   City                   478 non-null    object
 6   Tenure_Months          482 non-null    float64
 7   Subscription_Type      476 non-null    object
 8   Monthly_Charges        482 non-null    float64
 9   Total_Charges          482 non-null    float64
 10  Contract_Type          480 non-null    object
 11  Payment_Method         469 non-null    object
 12  Internet_Service       476 non-null    object
 13  Tech_Support           473 non-null    object
 14  Senior_Citizen         476 non-null    object
 15  Dependents             481 non-null    object
 16  Churn                  480 non-null    object
 17  Last_Interaction_Date  177 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(4), object(13)
memory usage: 71.5+ KB

In [30]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000+A2:A534,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,One Year,Upi,Fiber,Yes,No,Yes,No,2025-12-10
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,Month-To-Month,Debit Card,5G,No,No,No,Yes,NaT
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,2026-02-04
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-To-Month,Upi,Dsl,Yes,No,No,No,NaT
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,NaT

In [31]:
df['Subscription_Type']=df['Subscription_Type'].fillna('Unknown')
df['Payment_Method']=df['Payment_Method'].fillna('Unknown')
df['Tech_Support']=df['Tech_Support'].fillna('No')
df['Age']=df['Age'].fillna(df['Age'].mean())
df['Tenure_Months']=df['Tenure_Months'].fillna(df['Tenure_Months'].mean())
df['Monthly_Charges']=df['Monthly_Charges'].fillna(df['Monthly_Charges'].mean())
df['Total_Charges']=df['Total_Charges'].fillna(df['Total_Charges'].mean())
df['Last_Interaction_Date']=df['Last_Interaction_Date'].fillna(df['Last_Interaction_Date'].median())

# Feature Engineering

In [32]:
df['Customer_pay']=df['Monthly_Charges']*df['Tenure_Months']

In [33]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_pay
0,C1000+A2:A534,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,One Year,Upi,Fiber,Yes,No,Yes,No,2025-12-10,93627.08
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,Month-To-Month,Debit Card,5G,No,No,No,Yes,2025-08-11,7215.39
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,2026-02-04,1884.12
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-To-Month,Upi,Dsl,Yes,No,No,No,2025-08-11,140618.10
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,2025-08-11,125182.26

In [34]:
df['Monthly_Revenue']=df['Monthly_Charges']
df = df.drop('Monthly_Charges', axis=1)

In [35]:
#tenure grouping
bins =[0,15,30,45,60,75]
labels =["0-15 months","16-30 months","31-45 months","46-60 months","61-75 months"]
df['Tenure_Group']=pd.cut(df['Tenure_Months'],bins=bins,labels=labels)

In [36]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_pay,Monthly_Revenue,Tenure_Group
0,C1000+A2:A534,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,93273.08,One Year,Upi,Fiber,Yes,No,Yes,No,2025-12-10,93627.08,1614.26,46-60 months
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,6869.39,Month-To-Month,Debit Card,5G,No,No,No,Yes,2025-08-11,7215.39,555.03,0-15 months
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,2026-02-04,1884.12,314.02,0-15 months
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,140376.10,Month-To-Month,Upi,Dsl,Yes,No,No,No,2025-08-11,140618.10,2008.83,61-75 months
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,2025-08-11,125182.26,2196.18,46-60 months

In [37]:
#senior citizen flag

df['Senior_Flag']=np.where(df['Age']>=60,'Senior','Adult')

In [38]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Total_Charges,Contract_Type,...,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_pay,Monthly_Revenue,Tenure_Group,Senior_Flag
0,C1000+A2:A534,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,93273.08,One Year,...,Fiber,Yes,No,Yes,No,2025-12-10,93627.08,1614.26,46-60 months,Adult
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,6869.39,Month-To-Month,...,5G,No,No,No,Yes,2025-08-11,7215.39,555.03,0-15 months,Adult
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,1926.12,One Year,...,Cable,Yes,No,No,No,2026-02-04,1884.12,314.02,0-15 months,Adult
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,140376.10,Month-To-Month,...,Dsl,Yes,No,No,No,2025-08-11,140618.10,2008.83,61-75 months,Adult
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,125145.26,One Year,...,Cable,Yes,Yes,Yes,No,2025-08-11,125182.26,2196.18,46-60 months,Senior

In [39]:
df['Churn'].value_counts(dropna=False)

Churn
No     368
Yes    112
NaN      2
Name: count, dtype: int64

In [40]:
df = df.dropna(subset=['Churn'])

In [41]:
df['Churn'].value_counts(dropna=False)

Churn
No     368
Yes    112
Name: count, dtype: int64

In [42]:
#churn flag

df['Churn_Flag'] = df['Churn'].map({'Yes': 1, 'No': 0}).astype(int)

In [43]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Total_Charges,Contract_Type,...,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_pay,Monthly_Revenue,Tenure_Group,Senior_Flag,Churn_Flag
0,C1000+A2:A534,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,93273.08,One Year,...,Yes,No,Yes,No,2025-12-10,93627.08,1614.26,46-60 months,Adult,0
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,6869.39,Month-To-Month,...,No,No,No,Yes,2025-08-11,7215.39,555.03,0-15 months,Adult,1
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,1926.12,One Year,...,Yes,No,No,No,2026-02-04,1884.12,314.02,0-15 months,Adult,0
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,140376.10,Month-To-Month,...,Yes,No,No,No,2025-08-11,140618.10,2008.83,61-75 months,Adult,0
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,125145.26,One Year,...,Yes,Yes,Yes,No,2025-08-11,125182.26,2196.18,46-60 months,Senior,0

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 480 entries, 0 to 532
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            480 non-null    object
 1   Customer_Name          475 non-null    object
 2   Gender                 476 non-null    object
 3   Age                    480 non-null    float64
 4   State                  473 non-null    object
 5   City                   476 non-null    object
 6   Tenure_Months          480 non-null    float64
 7   Subscription_Type      480 non-null    object
 8   Total_Charges          480 non-null    float64
 9   Contract_Type          478 non-null    object
 10  Payment_Method         480 non-null    object
 11  Internet_Service       474 non-null    object
 12  Tech_Support           480 non-null    object
 13  Senior_Citizen         474 non-null    object
 14  Dependents             479 non-null    object
 15  Churn                  480 non-null    object
 16  Last_Interaction_Date  480 non-null    datetime64[ns]
 17  Customer_pay           480 non-null    float64
 18  Monthly_Revenue        480 non-null    float64
 19  Tenure_Group           480 non-null    category
 20  Senior_Flag            480 non-null    object
 21  Churn_Flag             480 non-null    int64
dtypes: category(1), datetime64[ns](1), float64(5), int64(1), object(14)
memory usage: 83.2+ KB

In [45]:
df.isnull().sum()

Customer_ID              0
Customer_Name            5
Gender                   4
Age                      0
State                    7
City                     4
Tenure_Months            0
Subscription_Type        0
Total_Charges            0
Contract_Type            2
Payment_Method           0
Internet_Service         6
Tech_Support             0
Senior_Citizen           6
Dependents               1
Churn                    0
Last_Interaction_Date    0
Customer_pay             0
Monthly_Revenue          0
Tenure_Group             0
Senior_Flag              0
Churn_Flag               0
dtype: int64

In [46]:
df.to_csv("Churn_Clean_Data.csv",index=False)

# Export into MySQL

In [47]:
%pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (2.1.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [48]:
%pip install pymysql

Requirement already satisfied: pymysql in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (1.2.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [49]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

password = quote_plus("Alisha@1234")

engine = create_engine(
    f"mysql+pymysql://root:{password}@localhost/churndb")

In [50]:
df.to_sql(
    name="customer_churn",
    con=engine,
    if_exists="replace",
    index=False
)

480